//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailFournisseur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTFOURNISS
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public string CT_Num { get; set; }
        public byte[] cbCT_Num { get; set; }
        public string AF_RefFourniss { get; set; }
        public byte[] cbAF_RefFourniss { get; set; }
        public Nullable<decimal> AF_PrixAch { get; set; }
        public Nullable<short> AF_Unite { get; set; }
        public Nullable<decimal> AF_Conversion { get; set; }
        public Nullable<short> AF_DelaiAppro { get; set; }
        public Nullable<short> AF_Garantie { get; set; }
        public Nullable<decimal> AF_Colisage { get; set; }
        public Nullable<decimal> AF_QteMini { get; set; }
        public Nullable<short> AF_QteMont { get; set; }
        public Nullable<short> EG_Champ { get; set; }
        public Nullable<short> AF_Principal { get; set; }
        public Nullable<decimal> AF_PrixDev { get; set; }
        public Nullable<short> AF_Devise { get; set; }
        public Nullable<decimal> AF_Remise { get; set; }
        public Nullable<decimal> AF_ConvDiv { get; set; }
        public Nullable<short> AF_TypeRem { get; set; }
        public string AF_CodeBarre { get; set; }
        public byte[] cbAF_CodeBarre { get; set; }
        public Nullable<decimal> AF_PrixAchNouv { get; set; }
        public Nullable<decimal> AF_PrixDevNouv { get; set; }
        public Nullable<decimal> AF_RemiseNouv { get; set; }
        public Nullable<System.DateTime> AF_DateApplication { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
    }
}
