//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailFournisseur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pf_csv
    {
        public int id_csv { get; set; }
        public string fichier { get; set; }
        public Nullable<System.DateTime> date_fichier { get; set; }
        public string fournisseur { get; set; }
    }
}
