//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailFournisseur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MP_ArtFournisseur
    {
        public string AR_Ref { get; set; }
        public string AR_Design { get; set; }
        public string FA_CodeFamille { get; set; }
        public Nullable<short> AR_Garantie { get; set; }
        public Nullable<decimal> AR_PoidsNet { get; set; }
        public Nullable<decimal> AR_PrixAch { get; set; }
        public string DEBUT_LIVRABILITE_PRINTEMPS { get; set; }
        public string FIN_LIVRABILITE_PRINTEMPS { get; set; }
        public string DEBUT_LIVRABILITE_AUTOMNE { get; set; }
        public string FIN_LIVRABILITE_AUTOMNE { get; set; }
        public string LIVRABLE_TOUTE_ANNEE { get; set; }
        public string HAUTEUR { get; set; }
        public string LARGEUR { get; set; }
        public string LONGUEUR { get; set; }
        public string CODE_STATUT { get; set; }
        public Nullable<decimal> AF_PrixAch { get; set; }
        public string LDF { get; set; }
        public string CT_Num { get; set; }
    }
}
