//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTICLE
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public string AR_Design { get; set; }
        public byte[] cbAR_Design { get; set; }
        public string FA_CodeFamille { get; set; }
        public byte[] cbFA_CodeFamille { get; set; }
        public string AR_Substitut { get; set; }
        public byte[] cbAR_Substitut { get; set; }
        public string AR_Raccourci { get; set; }
        public byte[] cbAR_Raccourci { get; set; }
        public Nullable<short> AR_Garantie { get; set; }
        public Nullable<short> AR_UnitePoids { get; set; }
        public Nullable<decimal> AR_PoidsNet { get; set; }
        public Nullable<decimal> AR_PoidsBrut { get; set; }
        public Nullable<short> AR_UniteVen { get; set; }
        public Nullable<decimal> AR_PrixAch { get; set; }
        public Nullable<decimal> AR_Coef { get; set; }
        public Nullable<decimal> AR_PrixVen { get; set; }
        public Nullable<short> AR_PrixTTC { get; set; }
        public Nullable<short> AR_Gamme1 { get; set; }
        public Nullable<short> AR_Gamme2 { get; set; }
        public Nullable<short> AR_SuiviStock { get; set; }
        public Nullable<short> AR_Nomencl { get; set; }
        public string AR_Stat01 { get; set; }
        public string AR_Stat02 { get; set; }
        public string AR_Stat03 { get; set; }
        public string AR_Stat04 { get; set; }
        public string AR_Stat05 { get; set; }
        public Nullable<short> AR_Escompte { get; set; }
        public Nullable<short> AR_Delai { get; set; }
        public Nullable<short> AR_HorsStat { get; set; }
        public Nullable<short> AR_VteDebit { get; set; }
        public Nullable<short> AR_NotImp { get; set; }
        public Nullable<short> AR_Sommeil { get; set; }
        public string AR_Langue1 { get; set; }
        public string AR_Langue2 { get; set; }
        public string AR_EdiCode { get; set; }
        public byte[] cbAR_EdiCode { get; set; }
        public string AR_CodeBarre { get; set; }
        public byte[] cbAR_CodeBarre { get; set; }
        public string AR_CodeFiscal { get; set; }
        public string AR_Pays { get; set; }
        public string AR_Frais01FR_Denomination { get; set; }
        public Nullable<decimal> AR_Frais01FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> AR_Frais01FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> AR_Frais01FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> AR_Frais01FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> AR_Frais01FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> AR_Frais01FR_Rem03REM_Type { get; set; }
        public string AR_Frais02FR_Denomination { get; set; }
        public Nullable<decimal> AR_Frais02FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> AR_Frais02FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> AR_Frais02FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> AR_Frais02FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> AR_Frais02FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> AR_Frais02FR_Rem03REM_Type { get; set; }
        public string AR_Frais03FR_Denomination { get; set; }
        public Nullable<decimal> AR_Frais03FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> AR_Frais03FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> AR_Frais03FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> AR_Frais03FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> AR_Frais03FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> AR_Frais03FR_Rem03REM_Type { get; set; }
        public Nullable<short> AR_Condition { get; set; }
        public Nullable<decimal> AR_PUNet { get; set; }
        public Nullable<short> AR_Contremarque { get; set; }
        public Nullable<short> AR_FactPoids { get; set; }
        public Nullable<short> AR_FactForfait { get; set; }
        public Nullable<System.DateTime> AR_DateCreation { get; set; }
        public Nullable<short> AR_SaisieVar { get; set; }
        public Nullable<short> AR_Transfere { get; set; }
        public Nullable<short> AR_Publie { get; set; }
        public Nullable<System.DateTime> AR_DateModif { get; set; }
        public string AR_Photo { get; set; }
        public Nullable<decimal> AR_PrixAchNouv { get; set; }
        public Nullable<decimal> AR_CoefNouv { get; set; }
        public Nullable<decimal> AR_PrixVenNouv { get; set; }
        public Nullable<System.DateTime> AR_DateApplication { get; set; }
        public Nullable<decimal> AR_CoutStd { get; set; }
        public Nullable<decimal> AR_QteComp { get; set; }
        public Nullable<decimal> AR_QteOperatoire { get; set; }
        public Nullable<int> CO_No { get; set; }
        public Nullable<int> cbCO_No { get; set; }
        public Nullable<short> AR_Prevision { get; set; }
        public Nullable<int> CL_No1 { get; set; }
        public Nullable<int> cbCL_No1 { get; set; }
        public Nullable<int> CL_No2 { get; set; }
        public Nullable<int> cbCL_No2 { get; set; }
        public Nullable<int> CL_No3 { get; set; }
        public Nullable<int> cbCL_No3 { get; set; }
        public Nullable<int> CL_No4 { get; set; }
        public Nullable<int> cbCL_No4 { get; set; }
        public Nullable<short> AR_Type { get; set; }
        public string RP_CodeDefaut { get; set; }
        public Nullable<short> AR_Nature { get; set; }
        public Nullable<short> AR_DelaiFabrication { get; set; }
        public Nullable<short> AR_NbColis { get; set; }
        public Nullable<short> AR_DelaiPeremption { get; set; }
        public Nullable<short> AR_DelaiSecurite { get; set; }
        public Nullable<short> AR_Fictif { get; set; }
        public Nullable<short> AR_SousTraitance { get; set; }
        public Nullable<short> AR_TypeLancement { get; set; }
        public Nullable<short> AR_Cycle { get; set; }
        public Nullable<short> AR_Criticite { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public string DEBUT_LIVRABILITE_PRINTEMPS { get; set; }
        public string FIN_LIVRABILITE_PRINTEMPS { get; set; }
        public string DEBUT_LIVRABILITE_AUTOMNE { get; set; }
        public string FIN_LIVRABILITE_AUTOMNE { get; set; }
        public string LIVRABLE_TOUTE_ANNEE { get; set; }
        public string MARQUE { get; set; }
        public string NB_PIECES_PAQUET { get; set; }
        public string HAUTEUR { get; set; }
        public string LARGEUR { get; set; }
        public string LONGUEUR { get; set; }
        public string HORS_NORME { get; set; }
        public string LDF { get; set; }
        public string BLOCAGE_CORSE { get; set; }
        public string BLOCAGE_BELGIQUE { get; set; }
        public string BLOCAGE_PAYS_BAS { get; set; }
        public string BLOCAGE_GRANDE_BRETAGNE { get; set; }
        public string BLOCAGE_ALLEMAGNE { get; set; }
        public string BLOCAGE_AUTRICHE { get; set; }
        public string BLOCAGE_PAYS_ETRANGERS { get; set; }
        public string EMPLACEMENT_PICKING { get; set; }
        public string CODE_STATUT { get; set; }
        public string INTITULE_FACTURE { get; set; }
        public string INTITULE_LATIN { get; set; }
        public string JYG { get; set; }
        public Nullable<decimal> VISIBLE { get; set; }
        public Nullable<decimal> POIDS_PLASTIQUE { get; set; }
        public string VENTE_SUGGESTIVE { get; set; }
    }
}
