//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hierarchie_be
    {
        public int id_table { get; set; }
        public string niveau { get; set; }
        public Nullable<int> idniv1 { get; set; }
        public Nullable<int> idniv2 { get; set; }
        public Nullable<int> idniv3 { get; set; }
        public Nullable<int> idniv4 { get; set; }
        public Nullable<int> idniv5 { get; set; }
        public Nullable<int> idniv6 { get; set; }
        public Nullable<int> id { get; set; }
        public string niveauComplet { get; set; }
        public Nullable<int> nbproduit { get; set; }
    }
}
