//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortailFournisseur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DOSSIER
    {
        public string D_RaisonSoc { get; set; }
        public string D_Profession { get; set; }
        public string D_Adresse { get; set; }
        public string D_Complement { get; set; }
        public string D_CodePostal { get; set; }
        public string D_Ville { get; set; }
        public string D_CodeRegion { get; set; }
        public string D_Pays { get; set; }
        public string D_Commentaire { get; set; }
        public string D_Siret { get; set; }
        public string D_Ape { get; set; }
        public string D_Identifiant { get; set; }
        public Nullable<System.DateTime> D_DebutExo01 { get; set; }
        public Nullable<System.DateTime> D_DebutExo02 { get; set; }
        public Nullable<System.DateTime> D_DebutExo03 { get; set; }
        public Nullable<System.DateTime> D_DebutExo04 { get; set; }
        public Nullable<System.DateTime> D_DebutExo05 { get; set; }
        public Nullable<System.DateTime> D_FinExo01 { get; set; }
        public Nullable<System.DateTime> D_FinExo02 { get; set; }
        public Nullable<System.DateTime> D_FinExo03 { get; set; }
        public Nullable<System.DateTime> D_FinExo04 { get; set; }
        public Nullable<System.DateTime> D_FinExo05 { get; set; }
        public Nullable<short> D_LgCg { get; set; }
        public Nullable<short> D_LgAn { get; set; }
        public string D_FormatQtes { get; set; }
        public Nullable<short> D_CodeTrait { get; set; }
        public Nullable<short> D_ConfSupp { get; set; }
        public Nullable<short> D_AnalyseGL01 { get; set; }
        public Nullable<short> D_AnalyseGL02 { get; set; }
        public Nullable<short> D_AnalyseGL03 { get; set; }
        public Nullable<short> D_Delai { get; set; }
        public Nullable<short> D_OuvCompte { get; set; }
        public Nullable<short> D_Budget { get; set; }
        public Nullable<short> D_SuppEc { get; set; }
        public Nullable<short> D_RegTaxe { get; set; }
        public Nullable<short> D_Ventil { get; set; }
        public Nullable<short> D_Edi { get; set; }
        public Nullable<short> D_Archivage01 { get; set; }
        public Nullable<short> D_Archivage02 { get; set; }
        public Nullable<short> D_Archivage03 { get; set; }
        public Nullable<short> D_Archivage04 { get; set; }
        public Nullable<short> D_Archivage05 { get; set; }
        public Nullable<short> D_RBSupp { get; set; }
        public Nullable<short> D_MajImport { get; set; }
        public Nullable<short> D_SaisCab { get; set; }
        public Nullable<short> D_TypeValid { get; set; }
        public Nullable<short> D_ImpressZero { get; set; }
        public Nullable<short> N_DeviseCompte { get; set; }
        public Nullable<short> N_DeviseEquival { get; set; }
        public Nullable<short> D_ANSais { get; set; }
        public string JO_NumAN { get; set; }
        public string CG_NumANOuv { get; set; }
        public string CG_NumANBenef { get; set; }
        public string CG_NumANPerte { get; set; }
        public Nullable<short> D_TVAEncReg { get; set; }
        public Nullable<short> D_TVAEncAffect { get; set; }
        public Nullable<short> D_DeviseEq { get; set; }
        public Nullable<short> D_AnAffect { get; set; }
        public Nullable<short> D_ReglPiece { get; set; }
        public Nullable<short> D_ExtNeg { get; set; }
        public Nullable<short> D_RapproDevise { get; set; }
        public Nullable<short> D_ImportEqJo { get; set; }
        public Nullable<short> D_ImportEqAn { get; set; }
        public string CG_NumImportDebit { get; set; }
        public string CG_NumImportCredit { get; set; }
        public Nullable<short> N_Analytique { get; set; }
        public string D_NumDoss { get; set; }
        public string D_EMail { get; set; }
        public string D_EMailExpert { get; set; }
        public string D_Expert { get; set; }
        public string D_Telephone { get; set; }
        public string D_Telecopie { get; set; }
        public string D_EMailSoc { get; set; }
        public string D_Site { get; set; }
        public Nullable<short> D_AppelTiers { get; set; }
        public Nullable<short> D_AppelSection { get; set; }
        public Nullable<short> D_ProtPiece { get; set; }
        public Nullable<short> D_NumCont { get; set; }
        public Nullable<System.DateTime> D_DateClot { get; set; }
        public Nullable<short> D_CompteGTotal { get; set; }
        public Nullable<short> D_RapproRecherche { get; set; }
        public Nullable<decimal> D_RapproEcart { get; set; }
        public string CG_NumRappro { get; set; }
        public Nullable<short> D_RapproContrepartie { get; set; }
        public Nullable<short> D_ComSens { get; set; }
        public Nullable<short> D_ComType { get; set; }
        public Nullable<short> D_ComMoyen { get; set; }
        public Nullable<short> D_ComSoft { get; set; }
        public string D_ComCodeExpert { get; set; }
        public Nullable<System.DateTime> D_ComDateSynchro { get; set; }
        public Nullable<System.Guid> D_ComGUID { get; set; }
        public Nullable<short> D_RapproTypeEcart { get; set; }
        public Nullable<short> D_RapproReport { get; set; }
        public string JO_NumRapproEscCl { get; set; }
        public Nullable<int> PI_NoRapproEscCl { get; set; }
        public string JO_NumRapproEscFr { get; set; }
        public Nullable<int> PI_NoRapproEscFr { get; set; }
        public Nullable<short> D_GestionIFRS { get; set; }
        public Nullable<short> D_SaisieIFRS { get; set; }
        public Nullable<short> N_AnalytiqueIFRS { get; set; }
        public string JA_NumAN { get; set; }
        public string JO_NumANIFRS { get; set; }
        public string JA_NumANIFRS { get; set; }
        public Nullable<decimal> D_RappelSoldeMin { get; set; }
        public Nullable<short> D_ImportVentil { get; set; }
        public Nullable<decimal> D_PenalTaux { get; set; }
        public Nullable<short> D_PenalImputation { get; set; }
        public string JO_NumPenal { get; set; }
        public Nullable<int> PI_NoPenal { get; set; }
        public string JO_NumImpayes { get; set; }
        public Nullable<int> PI_NoImpayes { get; set; }
        public Nullable<short> D_ImpressFactRef { get; set; }
        public Nullable<decimal> D_SeuilTVA { get; set; }
        public Nullable<short> D_NotSaisieSommeil { get; set; }
        public Nullable<System.DateTime> D_ArchivePeriod { get; set; }
        public Nullable<int> D_ECNoCloture01 { get; set; }
        public Nullable<int> D_ECNoCloture02 { get; set; }
        public Nullable<int> D_ECNoCloture03 { get; set; }
        public Nullable<int> D_ECNoCloture04 { get; set; }
        public Nullable<int> D_ECNoCloture05 { get; set; }
        public Nullable<System.DateTime> D_CloturePeriod { get; set; }
        public Nullable<short> D_MaterialPiece { get; set; }
        public Nullable<short> D_BudgetAn { get; set; }
        public Nullable<decimal> D_Capital { get; set; }
        public string D_FormeJuridique { get; set; }
        public Nullable<decimal> D_ForfaitImpayes { get; set; }
        public string D_CodeOctave { get; set; }
        public int cbMarq { get; set; }
        public string D_Facebook { get; set; }
        public string D_LinkedIn { get; set; }
        public Nullable<short> D_UpdateDevise { get; set; }
        public Nullable<short> D_UpdateDeviseSaisie { get; set; }
        public Nullable<short> D_Laf { get; set; }
        public Nullable<decimal> D_PasEcriture { get; set; }
        public Nullable<System.Guid> D_Logo { get; set; }
    }
}
