//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pf_colonne_csv
    {
        public int id { get; set; }
        public Nullable<int> id_csv { get; set; }
        public Nullable<int> id_colonne { get; set; }
        public string colonne { get; set; }
        public string id_fournisseur { get; set; }
        public string colonnewillemse { get; set; }
    }
}
